name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Wybierz wersję Node.js, która może być używana do testów lub buildów

    - name: Build and deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'budgetappfront'
        slot-name: 'production' # Opcjonalnie, jeśli używasz slotów
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
